version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: acme
    ports:
      - "3306:3306"            # Expose MySQL on port 3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .  # Build Spring Boot app from the Dockerfile
    container_name: harborlab-app
    ports:
      - "8080:8080"  # Expose Spring Boot app on port 8080
    environment:
      SPRING_APPLICATION_NAME: harborlab-acme
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/acme
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
